### Add a garden
POST http://localhost:8080/api/gardens
Content-Type: application/json

{
    "gardenName":"Garden 1"
}

### Patch garden:1
PATCH http://localhost:8080/api/gardens/1
Content-Type: application/json

{
    "gardenName":"A"
}


### Add a zone to garden:1
POST http://localhost:8080/api/gardens/1/zones
Content-Type: application/json

{
    "gardenZoneName":"Zone 1 in garden 1"
}

### Patch zone:2
PATCH http://localhost:8080/api/gardens/1/zones/2
Content-Type: application/json

{
    "gardenZoneName":"updatedzzz"
}

### Add a plant to zone:2
POST http://localhost:8080/api/gardens/1/zones/2/plants
Content-Type: application/json

{
    "plantName":"Plant 3 in zone 2 in garden 1"
}

### Patch plant:3
PATCH http://localhost:8080/api/gardens/1/zones/2/plants/3
Content-Type: application/json

{
    "plantName":"fuck 1"
}

### Delete a garden:1
DELETE http://localhost:8080/api/gardens/1

### Delete a zone:2
DELETE http://localhost:8080/api/gardens/1/zones/2

### Delete a plant:3
DELETE http://localhost:8080/api/gardens/1/zones/2/plants/3

